import "./globals.css";
import Footer from "../components/homepage/Footer";
import Navbar from "../components/homepage/Navbar";
import AccessibilityHeader from "../components/homepage/AccessibilityHeader";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <AccessibilityHeader /> */}
        <Navbar />
        <SidebarProvider>{children}</SidebarProvider>
        <Footer />
      </body>
    </html>
  );
}
