import "../globals.css";
import Footer from "../../components/homepage/Footer";
import Navbar from "../../components/homepage/Navbar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import UserIdInitializer from "@/components/UserIdInitializer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    // <body className={`antialiased`}>
    <>
      <UserIdInitializer />
      <Navbar position={"sticky"} />
      <SidebarProvider>
        <SidebarInset>{children}</SidebarInset>
      </SidebarProvider>
    </>
    // </body>
    // </html>
  );
}
